org: argot
app: neon-lambda
service: neon-lambda

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL: postgresql://neondb_owner:****************@ep-cold-pine-a5arwpmq.us-east-2.aws.neon.tech/neondb?sslmode=require

functions:
  # Existing Users endpoint
  getAllUsers:
    handler: users.getAllUsers
    events:
      - httpApi:
          path: /users
          method: get

  # Sales endpoints
  getSales:
    handler: logistics.getSales
    events:
      - httpApi:
          path: /sales
          method: get

  # Inventory endpoints
  getInventory:
    handler: logistics.getInventory
    events:
      - httpApi:
          path: /inventory
          method: get

  updateInventory:
    handler: logistics.updateInventory
    events:
      - httpApi:
          path: /inventory
          method: put

  # Fulfillment endpoints
  createFulfillment:
    handler: logistics.createFulfillment
    events:
      - httpApi:
          path: /fulfillment
          method: post

  getFulfillmentStatus:
    handler: logistics.getFulfillmentStatus
    events:
      - httpApi:
          path: /fulfillment/{fulfillment_id}
          method: get